### ISSUE TITLE
Stream issue in julia nightly (`1.11`) versus previous releases (e.g. `1.9.4`, or `1.10.0-rc3`)

### ISSUE THREAD

**Issue by t-bltg** [JuliaRandom/StableRNGs.jl#20]
```julia
import Random: seed!
using DelimitedFiles
using StableRNGs

const RNG = StableRNG(1_337)
let x = randn(RNG, 10_000)
  writedlm("x_$(VERSION.major).$(VERSION.minor).$(VERSION.patch).txt", x)
end

# VERSION v"1.11.0-DEV.1144"
```

```bash
$ diff -u x_1.9.4.txt x_1.11.0.txt
--- x_1.9.4.txt	2023-12-22 21:40:38.283439067 +0100
+++ x_1.11.0.txt	2023-12-22 21:40:33.043443219 +0100
@@ -4214,7 +4214,7 @@
 0.5745734638645761
 0.9050768627399978
 0.7998353512850861
-3.8845391427592286
+3.808418098649975
 -0.9209167676765456
 -0.8486914352114853
 -1.187370886634173
@@ -9456,7 +9456,7 @@
 -0.5560505044259424
 0.8707180694280159
 -0.11984053616248612
--3.7742838630507034
+-3.937332194065459
 -0.9957375309115277
 1.7041267859710465
 -0.9611494188778119
```

Causes nightly failure in `UnicodePlots` (https://github.com/JuliaPlots/UnicodePlots.jl/actions/runs/7300585284/job/19895531268).
Any hint about this ?

**Comment by ericphanson** [comment]
this is definitely a bug, but we need to figure out what changed upstream, and then vendor in the old code here so we can continue with the right numbers, similar to #17

**Comment by t-bltg** [comment]
`1.10.0-rc3` is not affected, I will try to bisect `1.11`.

**Comment by t-bltg** [comment]
Bisected to https://github.com/JuliaLang/julia/commit/ca5b4c5afb.

**Comment by rfourquet** [comment]
Thanks for bisecting!
Another suspect for v1.11: https://github.com/JuliaLang/julia/pull/52133, which I believe is not yet tested by StableRNGs.
