### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRandom/StableRNGs.jl#5]
Just wanted to open this issue to track the stability of this package, with the eventual goal of releasing 1.0.

cc: @rfourquet

**Comment by rfourquet** [comment]
Thanks for opening the discussion! I'm all for releasing 1.0, the only reason it's not done yet is that I wanted first to request feedback on whether it's problematic to bump versions from 0.1.2 to 1.0 when there are no breaking changes (and actually no changes at all). What do you think? I was thinking to ask on slack's #pkg-registration.

**Comment by rfourquet** [comment]
Version 1.0 is now released.
